services:
    Quinggu\OrderBundle\Service\OrderStatusService:
        arguments:
            - Quinggu\OrderBundle\Client\CarrierApiClient
            - Quinggu\OrderBundle\Client\SmsApiClient
            - '@doctrine.orm.entity_manager'
