services:
    Quinggu\OrderBundle\Service\OrderStatusService:
        class: Quinggu\OrderBundle\Service\OrderStatusService
        arguments:
            - Quinggu\OrderBundle\Client\CarrierApiClientInterface
            - Quinggu\OrderBundle\Client\SmsApiClientInterface
            - '@doctrine.orm.entity_manager'
